module.exports = {
  VIOLATION: {
    '1': 'Abandoned vehicle',
    '2': 'No parking at Pimlico event',
    '3': 'Impeding flow of traffic',
    '4': 'Snow emergency route',
    '5': 'Impeding movement of pedestrians',
    '6': 'Fire lane or handicapped',
    '7': 'Parking or parking meter tow-away zone',
    '8': 'No stopping/standing tow-away zone',
    '9': 'Commercial vehicle/residence over 20,000 lbs.',
    '10': 'Commercial vehicle/residence under 20,000 lbs.',
    '11': 'Residential parking',
    '12': 'No stopping/standing',
    '13': 'Blocking garage or driveway',
    '14': 'No stopping/parking stadium event on 33rd St.',
    '15': 'No stopping/parking stadium event Camden Yards',
    '16': 'No stopping/standing in transit stop',
    '17': 'Less than 15 feet from fire hydrant',
    '18': 'Other parking meter violation',
    '19': 'Exceeding 48 hour limit',
    '20': 'Passenger loading zone',
    '22': 'Expired tags',
    '23': 'Taxi stand',
    '25': 'Less than 30 feet from intersection',
    '26': 'No stopping/parking handicapped zone',
    '27': 'No stopping/parking street cleaning',
    '28': 'Cruising',
    '30': 'Red light',
    '31': 'Right on red',
    '32': 'Fixed speed camera',
    '33': 'Mobile speed camera',
    '34': 'Old speed camera',
    '41': 'No parking/standing in bike lanes',
    '42': 'Commercial vehicle impeding traffic flow',
    '43': 'Obstructing/impeding traffic crosswalk/intersection/school',
    '44': 'No parking/standing vendor truck',
    '45': 'No parking/standing motor home/camper/travel trailer',
    '46': 'No parking/standing In bus stop/bus Lane',
    '47': 'Obstructing/impeding traffic in an intersection or crosswalk',
    '50': 'Residential parking permit 2nd offense',
    '51': 'Residential parking permit 3rd offense',
    '52': 'Residential parking permit 4th offense',
    '99': 'Other/unknown violation'
  }
};
