service: baltimore-hows-my-driving

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 60

package:
  exclude:
    - .env
    - secrets.txt
    - package-lock.json
    - package.json
    - '*.spec.js'
    - coverage/**/*
    - .vscode/**/*
    - .nyc_output/**/*
    - twitter_scripts/**/*

functions:
  
  twitterWebhook:
    handler: handler.twitterWebhook
    events:
      - http:
          path: twitterWebhook
          method: post

  crcResponse:
    handler: handler.crcResponse
    events:
      - http:
          path: twitterWebhook
          method: get

  monthlyStats:
    handler: monthly.publishStats
    events:
      - schedule: cron(0 12 25 * ? *)

custom:
  prune:
    automatic: true
    number: 5