service: query

plugins:
  - serverless-offline

provider:
  name: aws
  stage: prod
  runtime: nodejs8.10
  region: us-east-1

functions:
  app:
    handler: query.handler
    events:
      - http: GET /query/
      - http: 'ANY {proxy+}'

